<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\AdminLTE-4.0.0-rc3\.github\codeql\codeql-config.yml" />
    <None Include="wwwroot\AdminLTE-4.0.0-rc3\.github\CONTRIBUTING.md" />
    <None Include="wwwroot\AdminLTE-4.0.0-rc3\.github\dependabot.yml" />
    <None Include="wwwroot\AdminLTE-4.0.0-rc3\.github\FUNDING.yml" />
    <None Include="wwwroot\AdminLTE-4.0.0-rc3\.github\ISSUE_TEMPLATE\bug-report-for-adminlte-v3.1-x.md" />
    <None Include="wwwroot\AdminLTE-4.0.0-rc3\.github\ISSUE_TEMPLATE\feature-request-for-adminlte-v4-x.md" />
    <None Include="wwwroot\AdminLTE-4.0.0-rc3\.github\workflows\bundlewatch.yml" />
    <None Include="wwwroot\AdminLTE-4.0.0-rc3\.github\workflows\codeql.yml" />
    <None Include="wwwroot\AdminLTE-4.0.0-rc3\.github\workflows\docs.yml" />
    <None Include="wwwroot\AdminLTE-4.0.0-rc3\.github\workflows\lint.yml" />
    <None Include="wwwroot\AdminLTE-4.0.0-rc3\.github\workflows\node-sass.yml" />
    <None Include="wwwroot\AdminLTE-4.0.0-rc3\.github\workflows\release.yml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BLL\BLL.csproj" />
    <ProjectReference Include="..\Entity\Entity.csproj" />
  </ItemGroup>

</Project>
